import "./styles/about.scss";
import "./styles/blog.scss";
import "./styles/contact.scss";
import "./styles/footer.scss";
import "./styles/header.scss";
import "./styles/home.scss";
import "./styles/services.scss";
import "./styles/style.scss";
import "./styles/variables.scss";
